#!/bin/bash
dist="" # weather information district
rain="" # rainfall information district
forecast_text="" # generalSituation, forecastDesc, outlook

cd # <path to program directory>
python3 epd4in2b_V2_display.py # <flags>

# --- Example ---
# dist="香港天文台"
# rain="油尖旺"
# forecast_text="generalSituation"

# cd /home/pi/WiHKger-edp3in7-epd4in2b/
# python3 epd4in2b_V2_display.py -d $dist -r $rain -f $forecast_text

# you may need to execute the following command the make this file executable:
# sudo chomd <path to this file>/epd4in2b_V2_refresh +x